config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  root 'pages#home'

  get 'alerts-listing', to: 'users#alerts'
  get 'subscribe', to: 'users#subscribe'
  get '/profile', to: 'users#profile'
  get '/all-alerts', to: 'alerts#all_alerts'
  post '/follow-on-tag', to: 'users#check_tag_follow'
  post '/follow-on-product', to: 'users#check_product_follow'
  post '/search', to: 'users#search'
  resources :alerts
  resources :products
  resources :tags
  resources :users, except: [:new]
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 3, maximum: 140 }
  validates :issue, presence: true, length: { minimum: 3 }
  validates :action, presence: true, length: { minimum: 3 }
  validates :source, presence: true, length: { minimum: 3 }
  has_many :concerns, dependent: :destroy
  has_many :tags, through: :concerns
  has_many :products, through: :tags
  has_many :alert_products, dependent: :destroy
  has_many :products, through: :alert_products
  has_many :p_users, through: :products, source: :users
  has_many :t_users, through: :tags, source: :users

  def users
    (self.t_users.all + self.p_users.all).uniq
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
   before_action :set_alert, only: [:edit, :update, :show, :destory]

   def index
     @alerts = Alert.all
   end

   def all_alerts
     @alerts = Alert.all.reverse
     render 'users/alerts'
   end

   def new
     @alert = Alert.new
   end

   def edit
   end

   def create
     @alert = Alert.new(alert_params)
     if @alert.save
      #  params[:alert][:tags].each do |tag|
      #    result = Tag.find_by(name: tag)
      #    @alert.concerns.create(tag_id: result.id) if result
      #  end
       params[:alert][:products].each do |product|
         result = Product.find_by(name: product)
         @alert.alert_products.create(product_id: result.id) if result
       end
       flash[:notice] = "Alert was successfully created"
       NotificationSenderJob.perform_later(@alert)
       redirect_to alert_path(@alert)
       else
       render 'new'
     end
   end

   def show
     @alert = Alert.select{|a| a.title.downcase.gsub(' ', '-') == params[:id]}.first unless @alert
   end

   def destroy
      Alert.find_by(id: params[:id]).destroy
      flash[:notice] = "Alert was successfully deleted"
      redirect_to alerts_path
   end

  def update
    if @alert.update(alert_params)
      @alert.concerns.destroy_all
      #  params[:alert][:tags].each do |tag|
      #    result = Tag.find_by(name: tag)
      #    @alert.concerns.create(tag_id: result.id) if result
      #  end
      @alert.alert_products.destroy_all
      params[:alert][:products].each do |product|
        result = Product.find_by(name: product)
        @alert.alert_products.create(product_id: result.id) if result
      end
      flash[:success] = "Alert was successfully updated"
      redirect_to alert_path(@alert)
      else
      render 'edit'
    end
  end

   private
     def set_alert
        @alert = Alert.find_by(id: params[:id])
     end

     def alert_params
         params.require(:alert).permit(:title, :issue, :action, :source)
     end

     def require_admin
        if current_user != !current_user.admin?
           flash[:danger] = "You can only create, edit or delete alerts if you are an admin"
           redirect_to root_path
        end
     end
end

app/views/alerts/_form.html.erb
<div class='form alert-actions'>
  <div class='wrapper'>
    <%= form_for(@alert, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group title">
        <%= f.label :title %>
        <%= "<span class='error-msg'>#{@alert.errors[:title].first}</span>".html_safe unless @alert.errors[:title].empty? %>
        <%= f.text_field :title, onkeyup: "check('.title')", class: "#{'failed' unless @alert.errors[:title].empty?}", autocomplete: "off" %>
      </div>
      <div class="form-group issue">
        <%= f.label :issue %>
        <%= "<span class='error-msg'>#{@alert.errors[:issue].first}</span>".html_safe unless @alert.errors[:issue].empty? %>
        <%= f.text_area :issue, onkeyup: "checkTextArea('.issue')", class: "#{'failed' unless @alert.errors[:issue].empty?}", autocomplete: "off" %>
      </div>
      <div class="form-group action">
        <%= f.label :action %>
        <%= "<span class='error-msg'>#{@alert.errors[:action].first}</span>".html_safe unless @alert.errors[:action].empty? %>
        <%= f.text_area :action, onkeyup: "checkTextArea('.action')", class: "#{'failed' unless @alert.errors[:action].empty?}", autocomplete: "off" %>
      </div>
      <div class="form-group source">
        <%= f.label :source %>
        <%= "<span class='error-msg'>#{@alert.errors[:source].first}</span>".html_safe unless @alert.errors[:source].empty? %>
        <%= f.text_field :source, onkeyup: "check('.source')", class: "#{'failed' unless @alert.errors[:source].empty?}", autocomplete: "off" %>
      </div>
      <div class="form-group">
        <%= f.label :products, class: 'up' %>
        <%= f.select :products, Product.all.collect { |product| product.name }, { :multiple => true, include_blank: false, selected: @alert.products.collect { |product| product.name } }, class: "form-control", multiple: 'multiple', size: Product.count > 5 ? 5 : Product.count %>
      </div>
      <!-- <div class="form-group">
        <%#= f.label :tags, class: 'up' %>
        <%#= f.select :tags, Tag.all.collect { |tag| tag.name }, { :multiple => true, include_blank: false, selected: @alert.tags.collect { |tag| tag.name } }, class: "form-control", multiple: 'multiple', size: Tag.count > 5 ? 5 : Tag.count %>
      </div> -->
      <%= submit_tag (action_name == 'new' ? "Create Alert" : "Update Alert"), class: 'btn btn-primary btn-lg form-submit' %>
    <% end %>

    <%= link_to "Back to alerts listing", alerts_path, class: 'back' %>
  </div>
</div>
<script>pageReady();</script>

app/views/alerts/alertlist.html.erb
<h1>Listing all alerts</h1>
<p>
    <%= link_to "Create new alert", new_alert_path %>
</p>
<table>
    <tr>
        <th>Title</th>
        <th>Issue</th>
    </tr>
    
    <% @alerts.each do |alert| %>
    <tr>
        <td><%= alert.title %></td>
        <td><%= alert.issue %></td>
        <td><%= link_to 'Edit'. edit_alert_path(alert) %></td>
        <td><%= link_to 'Show', alert_path(alert) %></td>
        <td><%= link_to 'Delete', alert_path(alert), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
    <% end %>
</table>

app/views/alerts/alerts.html.erb
<h1>Listing all alerts</h1>
<p>
    <%= link_to "Create new alert", new_alert_path %>
</p>
<table>
    <tr>
        <th>Title</th>
        <th>Issue</th>
    </tr>

    <% @alerts.each do |alert| %>
    <tr>
        <td><%= alert.title %></td>
        <td><%= alert.issue %></td>
        <td><%= link_to 'Edit', edit_alert_path(alert) %></td>
        <td><%= link_to 'Show', alert_path(alert) %></td>
        <td><%= link_to 'Delete', alert_path(alert), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
    <% end %>
</table>

app/views/alerts/edit.html.erb
<h1 align="center">Edit existing alert</h1>

<%= render 'form' %>

app/views/alerts/index.html.erb
<div class='alerts-wrapper'>
  <div class='alerts-header'>
    <h1>All existing alerts/services</h1>
    <%= link_to new_alert_path do %>
      <span>Add New</span>
    <% end %>
  </div>
  <div class="alerts-list">
    <% @alerts.each do |alert| %>
      <div class="alert-item">
        <h4><%= link_to alert.title, alert_path(alert.id) %></h4>
        <p><%= alert.created_at.strftime('%Y-%m-%d %H:%M') %></p>
        <span><%= alert.users.count %> users assigned</span>
        <%= link_to "Edit", edit_alert_path(alert.id) %>
        <%= link_to "Delete", alert_path(alert.id), method: :delete, data: {confirm: 'Are you sure?'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/alerts/new.html.erb
<h1 align="center">Create an alert</h1>

<%= render 'form' %>

app/views/alerts/show.html.erb
<div class="alert show">
  <div class='content'>
    <h1 align="center"><%= @alert.title %></h1>
    <ul>
      <% @alert.products.each do |product| %>
        <li><%= product.name %></li>
      <% end %>
      <% @alert.tags.each do |tag| %>
        <li><%= tag.name %></li>
      <% end %>
    </ul>
    <p class='issue'><%= @alert.issue %></p>
    <p class='action'><%= @alert.action %></p>
    <p class='source'>Source: <%= link_to @alert.source, @alert.source %></p>
    <p class='date'><%= @alert.created_at.strftime('%Y-%m-%d %H:%M') %></p>

    <% if current_user.admin %>
      <%= link_to "Edit this alert", edit_alert_path(@alert) %> |
    <% end %>
    <%= link_to "Go to subscribing page", '/subscribe' %> |
    <%= link_to "Back to alerts listing", (current_user.admin ? alerts_path : '/alerts-listing') %>
  </div>
</div>