config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  root 'pages#home'

  get 'alerts-listing', to: 'users#alerts'
  get 'subscribe', to: 'users#subscribe'
  get '/profile', to: 'users#profile'
  get '/all-alerts', to: 'alerts#all_alerts'
  post '/follow-on-tag', to: 'users#check_tag_follow'
  post '/follow-on-product', to: 'users#check_product_follow'
  post '/search', to: 'users#search'
  resources :alerts
  resources :products
  resources :tags
  resources :users, except: [:new]
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :preferences, dependent: :destroy
  has_many :users, through: :preferences
  has_many :concerns, dependent: :destroy
  has_many :alerts, through: :concerns
  has_many :product_tags, dependent: :destroy
  has_many :products, through: :product_tags
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :check_user

  def index
    @tags = Tag.all
  end

  def create
    @new_tag = Tag.create(name: params[:tag][:name])
    respond_to do |format|
      format.js
    end
  end

  def update
    Tag.find_by(id: params[:id]).update(name: params[:tag][:name])
    redirect_to tags_path
  end

  def edit
    @editin_tag = Tag.find_by(id: params[:id])
    respond_to do |format|
      format.js
    end
  end

  def destroy
    Tag.find_by(id: params[:id]).destroy
    redirect_to tags_path
  end

  private
    def check_user
      unless current_user.admin
        redirect_to '/'
      end
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class='item-edit'>
  <div class="form tag-editor out">
    <%= form_for @editin_tag do |f| %>
      <div class="form-group edit-name">
        <%= f.label :name, class: 'up' %>
        <%= f.text_field :name, onkeyup: "check('.edit-name')", autocomplete: "off", class: 'tag-name' %>
      </div>
      <%= submit_tag "Update tag", class: 'btn btn-primary btn-lg form-submit', disabled: 'disabled' %>
    <% end %>
  </div>
</div>

app/views/tags/create.js.erb
var html_str = "<div class='tag-item'><h4><%= @new_tag.name %></h4><span><%= @new_tag.products.count %> products assigned</span>"+
               "<span><%= @new_tag.alerts.count %> alerts assigned</span><span><%= @new_tag.users.count %> users subscribes</span>"+
               "<a href=<%= edit_tag_path(@new_tag.id) %> data-remote='true'>Edit</a><a href=<%= tag_path(@new_tag.id) %>"+
               " data-confirm='Are you sure?' rel='nofollow' data-method='delete'>Delete</a></div>";
$('.tags-list').append(html_str);
$('.tag-name').val('');
setTimeout(function(){
  $('.tag-creator .form-submit').attr('disabled', 'disabled');
}, 500)
$('.tag-creator').addClass('out');

app/views/tags/edit.js.erb
$("<%= escape_javascript(render(partial: 'form', :locals => {:editin_tag => @editin_tag })) %>")
.replaceAll(".item-edit");
$('.tag-item').removeClass('editing');
setTimeout(function(){
  $('.tag-editor').removeClass('out');
  $('.tag-item').each(function(index){
    if ($(this).find('h4').html()==$('.tag-editor .tag-name').val()) {
      $(this).addClass('editing');
    }
  })
}, 100);
pageReady();

app/views/tags/index.html.erb
<div class='tags-wrapper'>
  <div class='tags-header'>
    <h1>All existing tags</h1>
    <a class='add-new-tag'>
      <span>Add New</span>
    </a>
  </div>
  <div class="form tag-creator out">
    <%= form_for Tag.new, remote: true do |f| %>
      <div class="form-group name">
        <%= f.label :name %>
        <%= f.text_field :name, onkeyup: "check('.name')", autocomplete: "off", class: 'tag-name' %>
      </div>
      <%= submit_tag "Create new tag", class: 'btn btn-primary btn-lg form-submit', disabled: 'disabled' %>
    <% end %>
  </div>
  <div class='item-edit'></div>
  <div class="tags-list">
    <% @tags.each do |tag| %>
      <div class="tag-item">
        <h4><%= tag.name %></h4>
        <span><%= tag.products.count %> products assigned</span>
        <span><%= tag.alerts.count %> alerts assigned</span>
        <span><%= tag.users.count %> users subscribes</span>
        <%= link_to "Edit", edit_tag_path(tag.id), remote: true %>
        <%= link_to "Delete", tag_path(tag.id), method: :delete, data: {confirm: 'Are you sure?'} %>
      </div>
    <% end %>
  </div>
</div>
<script>pageReady();</script>