config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  root 'pages#home'

  get 'alerts-listing', to: 'users#alerts'
  get 'subscribe', to: 'users#subscribe'
  get '/profile', to: 'users#profile'
  get '/all-alerts', to: 'alerts#all_alerts'
  post '/follow-on-tag', to: 'users#check_tag_follow'
  post '/follow-on-product', to: 'users#check_product_follow'
  post '/search', to: 'users#search'
  resources :alerts
  resources :products
  resources :tags
  resources :users, except: [:new]
end

app/views/layouts/_footer.html.erb
<footer>
  <div class='footer'>
    <p>© 2017 BONSHO. All Rights Reserved.</p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%="#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
      <% end %>
    </div>
  </div>
  

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BONSHO", current_user ? '/alerts-listing' : root_path, class: "navbar_brand", id: "logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if action_name == 'home' %>
          <li><a href="#" class='move-to-about'>About</a></li>
        <% else %>
          <li><%= link_to "Alerts", '/alerts-listing' %></li>
          <li><%= link_to "Evailable Alerts", '/all-alerts' %></li>
          <li><%= link_to "Subscribe on alerts", '/subscribe' %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="/profile">Profile</a></li>
              <% if current_user.admin %>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Alerts', alerts_path %></li>
                <li><%= link_to 'Products', products_path %></li>
                <!-- <li><%#= link_to 'Tags', tags_path %></li> -->
              <% end %>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BONSHO - Vigilance as a Service</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%#= render 'layouts/messages' %>
  <div class='container-wrapper'>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>